name: primeiro-workflow
run-name: Meu Primeiro Workflow

# on: [push]

#event 
on:
    push:
        branches:
            - main

jobs:
    mac:
        runs-on: macos-latest
        steps:
            - name: Rodar um hello no mac
              run: echo "Rodou no MAC"
    linux:
        runs-on: ubuntu-latest
        steps:
            - name: Rodar um hello no linux
              run: echo "Rodou no Linux tambem"
